trigger:
  branches:
    include:
      - alpha
      - stable

pr:
  branches:
    include:
      - alpha
      - stable

resources:
  repositories:
    - repository: pipelines
      type: github
      name: DraviaVemal/azure-pipeline
      endpoint: github.com_DraviaVemal
      ref: refs/heads/alpha

extends:
  template: oss/xml_rs/pipeline.yml@pipelines
