trigger:
  branches:
    include:
      - release
  tags:
    include:
      - v*
    exclude:
      - v*-*

pr:
  branches:
    include:
      - release

resources:
  repositories:
    - repository: pipelines
      type: github
      name: DraviaVemal/azure-pipeline
      endpoint: github.com_DraviaVemal
      ref: refs/heads/release

extends:
  template: oss/xml_rs/pipeline.yml@pipelines
